version: "3"
services:
    bot:
        build:
          context: .
          dockerfile: ./src/telegram_bot/Dockerfile
        env_file: .env
        container_name: vimeo-angel-bot
        restart: always
        ports:
            - "3000:3000"
            - "5000:5000"
            - "80:80"
            - "443:443"
            - "5222:5222"
        volumes:
            - ./:/usr/src/bot

    mtproto-api:
        build: 
          context: .
          dockerfile: ./src/telegram-bot-api/Dockerfile
        env_file: .env
        container_name: vimeo-angel-mtproto-api
        restart: always
        ports:
            - "3000:3000"
            - "5000:5000"
            - "80:80"
            - "443:443"
            - "5222:5222"
        volumes:
            - ./:/usr/src/mtproto-api