version: "3"
services:
    bot-core:
        build:
          context: .
          dockerfile: ./src/telegram_bot/Dockerfile
        env_file: .env
        environment:
            CHOKIDAR_USEPOLLING: "true"
        container_name: bot-core
        restart: always
        ports:
            - "3000:3000"
            - "5000:5000"
            - "80:80"
            - "443:443"
            - "5222:5222"
        volumes:
            - ./:/usr/src/bot
            - ./telegram-bot-api-data:/var/lib/telegram-bot-api:ro
            - C:\Users\rol44\Videos\Recordings:/var/lib/telegram-bot-api/watch
        entrypoint: ["bash", "-c", "tsc && npm run start-prod-server"]
    telegram-bot-api:
        image: aiogram/telegram-bot-api:latest
        volumes:
            - ./telegram-bot-api-data:/var/lib/telegram-bot-api
        ports:
            - 8081:8081
        env_file:
            - .env
        environment:
            TELEGRAM_LOCAL: "true"
        restart: always 
    